from Smart_Nanny.SmartNanny_backend.customer_backend.methods.insert_customer import customer_id
from Smart_Nanny.SmartNanny_backend.nanny_backend.method.connecting_nanny_collection_to_customer_collection import nanny_id
from Smart_Nanny.SmartNanny_backend.customer_backend.classes.class_customer_collection import CustomerCollection

customer_collection = CustomerCollection("SmartNanny", "Customer")

customer_collection.connecting_nanny_to_customer(customer_id, nanny_id)
